[theme]

base = "light"

primaryColor = "#502D55"

backgroundColor = "#F8F4E9"

secondaryBackgroundColor = "#F8F4E9"

textColor = "#502D55"

borderColor = "#935073"

dataframeBorderColor = "#935073"

dataframeHeaderBackgroundColor = "#502D55"

showWidgetBorder = true

chartCategoricalColors = [
    "#502D55",
    "#935073",
    "#F6DBC0"
]

linkColor = "#502D55"

codeTextColor = "#502D55"

codeBackgroundColor = "#F8F4E9"
